name: build-action

on:
  push:
    branches: [ main, develop, develop/*, develop*, feature*, feature/*, task*, task/*, hotfix*, hotfix/*]
  pull_request:
    branches: [ main, develop, develop/*, develop*, feature*, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: get premake5
      run: |
       wget -qO- https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz | \
       tar xvz premake5 | \
       xargs -I"{}" sudo mv {} /usr/bin

    - name: generate Makefiles
      run: premake5 --file=premake5.lua gmake

    - name: get dependencies
      run: DEBIAN_FRONTEND=noninteractive sudo apt-get update -yqq --allow-releaseinfo-change -o::Dpkg::Use-Pty=0 && DEBIAN_FRONTEND=noninteractive sudo apt-get install -yqq -o::Dpkg::Use-Pty=0 libopenal-dev build-essential libgl1-mesa-dev libglm-dev libglfw3-dev ocl-icd-opencl-dev libc++abi-dev

      # TODO(algo-ryth-mix): there is an error here somewhere (sometimes old stuff is used)
      # the below two steps are here to aid in finding the bugs and should be removed when ironed out

    - name: probe commit
      run: git log -p -2 || true

    - name: make
      run: make CXX=clang++-12 config=debug64 all

    - name: run unit tests
      run: cp -R applications/unit_tests/assets . && bin/Debug64/unit_tests -nobenchmark



    # TODO(algo-ryth-mix): here I need to publish artifacts. this is currently still a bit of a mystery to me
    # should the artifacts be published as single libraries or should we gzip them together ? or both ?
